### PR TITLE
header: add support for reading secondary header

### PR DESCRIPTION
**Pull request by lucab**
This adds support for secondary header, as well as minor fixes
for larger sector sizes and underflow checks.
This is low-level support, not exposed yet in the public API.

### CODE REVIEW

**Comment by lucab** [comment]
Rebased to get rid of conflicts, PTAL.

For reference, I plan to submit a couple more PRs to expose this via a coherent high-level interface, but later (as soon as I have time for it).

**Comment by cholcombe973** [comment]
I was kinda hoping we could find the sector size instead of hard coding it but it looks like the only way to do that is with an ioctl call.  I'm not sure what to do with that.  Maybe just leave it hard coded for now

**Comment by lucab** [comment]
I'm planning to plumb that through from the higher level disk config, so that the same value applies and can be changed from a single knob. And likely turn it into a single 512-or-4096 enum. Final details still pending. I'm not sure if there is a unified simple way to determine logical block size.

**Comment by lucab** [comment]
I can leave it out of this PR if you prefer but I'd still like to introduce it at some point, so I figured out I can start adapting internal functions as I go. Let me know your preference.

**Comment by cholcombe973** [comment]
Yeah I'd say leave it in for now.  Sounds like you've given it some thought.  If I find an easy way to find it I'll let you know :)

**Pull request merged**
