### PR TITLE
Write partitions

### PR DESCRIPTION
**Pull request by cholcombe973**
Partition creation support.

### CODE REVIEW

**Comment by cholcombe973** [comment]
This still needs a partition creation test case.  Coming shortly

**Comment by lucab** [comment]
Ping, any way we can push this forward?

**Comment by cholcombe973** [comment]
@lucab try version 0.2.1 and let us know how it goes :)

**Comment by lucab** [comment]
Oh, that was a quick turnaround, thanks! I'll give it a try soon.

**Pull request merged**
